### ISSUE TITLE
The plug-in execution failed because the Sandbox Client encountered an error during initialization.

### ISSUE THREAD

**Issue by hrhgl** [a33ik/UltimateWorkflowToolkit#44]
Microsoft Dynamics 365
Version 2104 (9.1.3.11) (DB 9.1.3.11) on-premises

Sync workflow failed with error message - Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: The plug-in execution failed because the Sandbox Client encountered an error during initialization.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.EnsureListenerStarted()
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass26_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

Exception type: Microsoft.Crm.Workflow.Services.InvalidCustomActivityExecutionException
Message: The plug-in execution failed because the Sandbox Client encountered an error during initialization.
   at System.Activities.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow, IDictionary`2 inputs, TimeSpan timeout, WorkflowInstanceExtensionManager extensions)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.ExecuteWorkflowUsingInvoker(Activity workflow, ICommonWorkflowContext context)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.StartWorkflow(WorkflowActivationData activationData, ICommonWorkflowContext context)
-- End stack trace --

, error code - -2147220891

**Comment by hrhgl** [comment]
I can handle this error by replacing Microsoft.Dynamics.Sales.Plugins.dll with the old one (11/02/2018) in web view, but this solution doesn't work for the unified interface.

**Comment by AndrewButenko** [comment]
Unfortunately, you didn't give me much info regarding what doesn't work.
